# Generated by Django 3.2.5 on 2022-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='data',
            field=models.FileField(upload_to=''),
        ),
    ]
