# Generated by Django 3.2.5 on 2022-05-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vector', '0002_alter_jsonfile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='data',
            field=models.TextField(),
        ),
    ]
